//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTask6.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetTask6.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить фильм &quot;{0}&quot;?.
        /// </summary>
        internal static string ApproveDeleteMovie {
            get {
                return ResourceManager.GetString("ApproveDeleteMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        internal static string ApproveDeleteMovieCaption {
            get {
                return ResourceManager.GetString("ApproveDeleteMovieCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все фильмы.
        /// </summary>
        internal static string GridTitleAllMovies {
            get {
                return ResourceManager.GetString("GridTitleAllMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string GridTitleLoading {
            get {
                return ResourceManager.GetString("GridTitleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска по критерию: {0}.
        /// </summary>
        internal static string GridTitleSearchResult {
            get {
                return ResourceManager.GetString("GridTitleSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MovieImagePlaceholder {
            get {
                object obj = ResourceManager.GetObject("MovieImagePlaceholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный год (должен быть &gt;= {0} и не в будущем).
        /// </summary>
        internal static string YearInputInvalid {
            get {
                return ResourceManager.GetString("YearInputInvalid", resourceCulture);
            }
        }
    }
}
